import { Inter } from "next/font/google";
import Navbar from "../components/Navbar";
import "./globals.css";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
          <div className="grid place-items-center bg-blue-100 h-screen px-6 font-sans">
            <Navbar />
            {children}
          </div>
      </body>
    </html>
  );
}
